sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2858
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSkxZFAqmi1WdeczGV6
    access-key-secret: QFKYKykyaGn8Y83aEVIEzniRwcQkRW
    bucket-name: cctong
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx3d9156270de97630
    secret: 57b37581dc665d5275b03ca793dc9541